### ISSUE TITLE
Add package to MELPA

### ISSUE THREAD

**Issue by ghost** [mguzmann/company-ipa#2]
Hi. This is mainly a reminder to myself to install this amazing package once it hits MELPA (since you will close this once you put it in MELPA).

**Comment by mguzmann** [comment]
Thanks for the remainder that I have to put this in MLEPA!

**Comment by mguzmann** [comment]
this is now on MELPA and the offical repo in gitlab. I'll keep this as a mirror. I'll update it later today.
